// front-end/vue/src/controls/confirm-dialog/confirm-dialog.vue
<template>
  <ctr-dialog :visible="visible" :title="title" :showOkButton="showOkButton"
    :showCancelButton="showCancelButton" :modalClickable="modalClickable" :okButtonText="okButtonText"
    :cancelButtonText="cancelButtonText" :loading="loading" @closeEvent="onClose" @cancelEvent="onCancel">
    <slot></slot>
  </ctr-dialog>
</template>

<script lang="ts" src="./confirm-dialog.ts"></script>

// front-end/react/src/app/controls/confirm-dialog/ConfirmDialog.tsx
import React from 'react';
import { Dialog } from '..';
import { TextService } from '@/app/utils';

export interface ConfirmDialogProps {
  visible?: boolean;
  title?: string;
  showOkButton?: boolean;
  showCancelButton?: boolean;
  okButtonText?: string;
  cancelButtonText?: string;
  children?: React.ReactNode;
  isLoading?: boolean;
  onClose?: () => void;
  onOk?: () => void;
  onCancel?: () => void;
}

export const ConfirmDialog = ({
  visible,
  children,
  title,
  showOkButton = true,
  showCancelButton = true,
  okButtonText = TextService.controls.confirm,
  cancelButtonText = TextService.controls.cancel,
  onOk,
  onCancel,
  onClose,
  isLoading,
}: ConfirmDialogProps) => {
  return (
    <Dialog
      visible={visible}
      title={title}
      isLoading={isLoading}
      showOkButton={showOkButton}
      showCancelButton={showCancelButton}
      okButtonText={okButtonText}
      cancelButtonText={cancelButtonText}
      onOk={onOk}
      onCancel={onCancel}
      onClose={onClose}
    >
      {children}
    </Dialog>
  );
};
