// front-end/react/src/app/home/page.tsx
'use client';
import React, { useEffect, useState } from 'react';
import { SystemBusiness } from '../../business';
import { StringService } from '../../utils';
import './home.scss';

export default function Home() {
  const [readMeContent, setReadMeContent] = useState<string[]>([]);

  useEffect(() => {
    getReadMe();
  }, []);

  const getReadMe = () => {
    SystemBusiness.getReadMe().then((data) => {
      setReadMeContent(StringService.markDownToHTML(data));
    });
  };

  return (
    <div className="home-view">
      <div className="content-wrapper">
        {readMeContent.map((item, index) => (
          <div dangerouslySetInnerHTML={{ __html: item }} key={index}></div>
        ))}
      </div>
    </div>
  );
}

// front-end/vue/src/views/home/home.vue
<template>
  <div class="home-view">
    <div class="content-wrapper">
      <div v-html="item" v-for="(item, index) in readMeContent" :key="index"></div>
    </div>
  </div>
</template>

<script lang="ts" src="./home.ts"></script>
<style lang="scss" scoped="" type="text/css" src="./home.scss"></style>
