// front-end/react/src/controls/tree/tree-node/tree-node.tsx
import React, { useEffect, useState } from 'react';
import { TreeNodeItem, setCheckStatus } from '../tree-helper';
import './tree-node.scss';
import Link from 'next/link';

export interface TreeNodeProps {
  showCheckbox?: boolean;
  items?: TreeNodeItem[];
  theme?: 'white' | '';
  className?: string;
  selectItem?: (item: TreeNodeItem) => void;
}

export const TreeNode = ({
  items = [],
  selectItem,
  theme,
  className,
  showCheckbox,
}: TreeNodeProps) => {
  const [nodes, setNodes] = useState(items);

  useEffect(() => {
    setNodes(items);
  }, [items]);

  const onSelectItem = (menu: TreeNodeItem) => {
    selectItem && selectItem(menu);
    if (!menu.url) {
      menu.checked = !menu.checked;
      setNodes([...nodes]);
    }
  };

  const onExpand = (menu: TreeNodeItem, expanded: boolean) => {
    menu.expanded = expanded;
    setNodes([...nodes]);
  };

  const onCheckItem = (item: TreeNodeItem) => {
    item.checked = !item.checked;
    setCheckStatus(item.children, item.checked);
    setNodes([...nodes]);
  };

  const renderNodes = (nodes || []).map((item, index) => (
    <div
      key={item.id || index}
      className={['ctr-tree-node', className].join(' ')}
    >
      <div className={'ctr-tree-node-name theme-' + theme}>
        {(item.children || []).length > 0 ? (
          <span className="ctr-tree-node-icon">
            {item.expanded ? (
              <i
                onClick={() => onExpand(item, false)}
                className="fa fa-minus-square-o expand-icon"
              ></i>
            ) : (
              <i
                onClick={() => onExpand(item, true)}
                className="fa fa-plus-square-o expand-icon"
              ></i>
            )}
          </span>
        ) : null}
        <span
          className={
            (item.selected ? 'ctr-tree-node-name-selected ' : '') +
            'ctr-tree-node-name-item'
          }
        >
          <span className={!item.children?.length ? 'leaf-with-parent' : ''}>
            {showCheckbox ? (
              <input
                checked={item.checked || false}
                onClick={() => onCheckItem(item)}
                onChange={() => {}}
                className="node-checkbox"
                type="checkbox"
              />
            ) : null}
            <span
              className="ctr-tree-node-name-text"
              onClick={() => onSelectItem(item)}
            >
              {!item.url ? (
                <span className="node-text-wrapper">{item.name}</span>
              ) : (
                <Link href={item.url} className="node-text-wrapper">
                  {item.name}
                </Link>
              )}
            </span>
          </span>
        </span>
      </div>
      {(item.children || []).length > 0 ? (
        <span className={item.expanded ? '' : 'hidden'}>
          <TreeNode
            items={item.children}
            showCheckbox={showCheckbox}
            selectItem={(e) => onSelectItem(e)}
          ></TreeNode>
        </span>
      ) : null}
    </div>
  ));

  return <div className="ctr-tree-child">{renderNodes}</div>;
};

// front-end/vue/src/controls/tree/tree-node/tree-node.vue
<template>
  <div class="ctr-tree-child">
    <div v-for="(item, index) in items" :key="item.id || index" class="ctr-tree-node">
      <div :class="'ctr-tree-node-name theme-' + theme">
        <span v-if="item.children && item.children.length > 0">
          <span class="ctr-tree-node-icon">
            <i v-if="item.expanded" @click="onExpand(item, false)" class="fa fa-minus-square-o expand-icon"></i>
            <i v-else @click="onExpand(item, true)" class="fa fa-plus-square-o expand-icon"></i>
          </span>
        </span>
        <span class="ctr-tree-node-name-item" :class="item.selected ? 'ctr-tree-node-name-selected' : ''">
          <span :class="!item.children?.length ? 'leaf-with-parent' : ''">
            <input v-if="showCheckbox" :checked="item.checked" @click="onCheckItem(item)" class="node-checkbox"
              type="checkbox" />
            <span class="ctr-tree-node-name-text" @click="onSelectItem(item)">
              <span class="node-text-wrapper" v-if="!item.url">{{ item.name }}</span>
              <router-link class="node-text-wrapper" v-else :to="item.url">{{ item.name }}</router-link>
            </span>
          </span>
        </span>
      </div>
      <span v-if="item.children && item.children.length > 0" v-show="item.expanded">
        <tree-node :items="item.children" :showCheckbox="showCheckbox" @selectItem="onSelectItem($event)"></tree-node>
      </span>
    </div>
  </div>
</template>

<script lang="ts" src="./tree-node.ts"></script>
<style lang="scss" scoped src="./tree-node.scss"></style>
