// front-end/react/src/controls/input/input.tsx
import React from 'react';
import './input.scss';

export interface InputProps
  extends React.DetailedHTMLProps<
    React.InputHTMLAttributes<HTMLInputElement>,
    HTMLInputElement
  > {
  showClearButton?: boolean;
  showError?: boolean;
  errorMessage?: string;
  onClear?: () => void;
}

export const Input = ({
  value,
  type,
  showError,
  onClear,
  errorMessage,
  showClearButton = false,
  ...props
}: InputProps) => {
  const clickClear = () => {
    onClear && onClear();
  };

  return (
    <span className="ctr-input">
      <input
        type={type || 'text'}
        value={value}
        className={['control-input', showError ? 'input-error' : ''].join(' ')}
        {...props}
      />
      {showError && errorMessage ? (
        <span className="error-message">{errorMessage}</span>
      ) : null}
      {showClearButton && value ? (
        <i className="fa fa-close" onClick={() => clickClear()}></i>
      ) : null}
    </span>
  );
};

// front-end/vue/src/controls/input/input.vue
<template>
  <span class="ctr-input">
    <input v-focus="focus" :type="type" :readonly="readonly" :disabled="disabled" :placeholder="placeholder"
      :value="modelValue" :class="['control-input', error ? 'input-error' : '', customClass]"
      @keyup.enter="onEnter($event)" @input="onInputChange($event)" />
    <span class="error-message" v-if="error && errorMessage">
      {{ errorMessage }}
    </span>
    <i class="fa fa-close" v-if="showClearButton && modelValue" @click="onClear"></i>
  </span>
</template>

<script lang="ts" src="./input.ts"></script>
<style lang="scss" scoped src="./input.scss"></style>
