// front-end/react/src/controls/button/button.tsx

import React, { ButtonHTMLAttributes, DetailedHTMLProps } from 'react';
import Image from 'next/image';
import './button.scss';

export interface ButtonProps
  extends DetailedHTMLProps<
    ButtonHTMLAttributes<HTMLButtonElement>,
    HTMLButtonElement
  > {
  isLoading?: boolean;
  role?: 'primary' | 'secondary';
  state?: 1 | 2 | 3;
  size?: 'small' | '';
}

export const Button = ({
  disabled,
  isLoading,
  children,
  className,
  role,
  state = 1,
  size,
  onClick,
  ...props
}: ButtonProps) => {
  return (
    <span className="ctr-button">
      <button
        type="button"
        disabled={state > 1 ? true : false}
        className={
          'btn btn-' +
          state +
          ' control-button ' +
          (size ? 'btn-' + size : '') +
          ' ' +
          className
        }
        onClick={(e) => onClick && onClick(e)}
        {...props}
      >
        {state === 3 && (
          <span className={'icon-box'}>
            <Image
              className="icon-loading"
              src="/assets/images/loading.gif"
              alt=""
              width="20"
              height="20"
            />
          </span>
        )}
        {children}
      </button>
    </span>
  );
};

// front-end/vue/src/controls/button/button.vue
<template>
  <span class="ctr-button">
    <button type="button" :disabled="state !== 1"
      :class="['btn', 'btn-' + type, 'control-button', size ? 'btn-' + size : '', customClass]" @click="onClick">
      <div v-show="state === 3" class="icon-box">
        <img class="icon-loading" src="../../assets/images/loading.gif" />
      </div>
      {{ text }}
    </button>
  </span>
</template>

<script lang="ts" src="./button.ts"></script>
<style lang="scss" scoped src="./button.scss"></style>
