// front-end/react/src/app/roles/_access-control/access-control.tsx
import React, { useCallback, useEffect, useState } from 'react';
import { Tree, Loading } from '../../../controls';
import {
  expandAll,
  checkAll,
  clearUrl,
  checkTargets,
  getCheckedIds,
} from '../../../controls';
import { RoleBusiness, SystemBusiness } from '../../../business';
import { ToastService, TextService } from '../../../utils';
import { Role } from '../../../models';
import './access-control.scss';

export interface AccessControlProps {
  item?: Role;
  cancelEvent?: () => void;
  instance?: (params: { save: () => void }) => void;
}

export const AccessControl = ({
  item = {},
  cancelEvent,
  instance,
}: AccessControlProps) => {
  const controlsText = TextService.controls;
  const [menus, setMenus] = useState(SystemBusiness.getSystemMenus());
  const [isLoading, setIsLoading] = useState(true);
  clearUrl(menus);
  expandAll(menus, true);

  const getRoleAccessList = useCallback(() => {
    if (item) {
      RoleBusiness.getAccessList(Number(item.roleId))
        .then((data) => {
          setIsLoading(false);
          checkTargets(menus, data);
        })
        .catch((err) => {
          setIsLoading(false);
          ToastService.notify(err, 'error');
        });
    }
  }, [item, menus]);

  useEffect(() => {
    getRoleAccessList();
  }, [getRoleAccessList]);

  const onCheckAll = (checked: boolean) => {
    checkAll(menus, checked);
    setMenus([...menus]);
  };

  const save = () => {
    if (isLoading) {
      return;
    }

    setIsLoading(true);
    RoleBusiness.saveAccessList(Number(item.roleId), getCheckedIds(menus))
      .then(() => {
        setIsLoading(false);
        cancelEvent && cancelEvent();
      })
      .catch((err: string) => {
        setIsLoading(false);
        cancelEvent && cancelEvent();
        ToastService.notify(err, 'error');
      });
  };
  instance && instance({ save });

  return (
    <div className="com-access-control">
      {!isLoading ? (
        <div>
          <div className="link-button-row">
            <span className="link-button" onClick={() => onCheckAll(true)}>
              {controlsText.checkAll}
            </span>
            <span className="link-button" onClick={() => onCheckAll(false)}>
              {controlsText.uncheckAll}
            </span>
          </div>
          <Tree items={menus} showCheckbox={true}></Tree>
        </div>
      ) : (
        <Loading></Loading>
      )}
    </div>
  );
};

export default AccessControl;

// front-end/vue/src/views/roles/access-control/access-control.vue
<template>
  <div class="com-access-control">
    <div v-if="!loading">
      <div class="link-button-row">
        <span class="link-button" @click="onCheckAll(true)">{{controls.checkAll}}</span>
        <span class="link-button" @click="onCheckAll(false)">{{controls.uncheckAll}}</span>
      </div>
      <ctr-tree
        :items="menus"
        :showCheckbox="true"></ctr-tree>
    </div>
    <ctr-loading :absolute="true" v-else></ctr-loading>
  </div>
</template>

<script lang="ts" src="./access-control.ts"></script>
<style lang="scss" scoped type="text/css" src="./access-control.scss"></style>
