// front-end/react/src/app/roles/_role-edit/role-edit.tsx
import React, { useState } from 'react';
import { Button, Input } from '../../../controls';
import { RoleBusiness } from '../../../business';
import { ToastService, TextService } from '../../../utils';
import { Role } from '../../../models';
import './role-edit.scss';

export interface RoleEditProps {
  item?: Role;
  cancelEvent?: () => void;
  saveEvent?: () => void;
}

export const RoleEdit = ({ item = {}, saveEvent, cancelEvent }: RoleEditProps) => {
  const controlsText = TextService.controls;
  const messagesText = TextService.messages;
  const [isLoading, setIsLoading] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  const [editingItem, setEditingItem] = useState(item);

  const onSave = () => {
    if (isLoading) {
      return;
    }

    setIsLoading(true);
    setSubmitted(true);
    const method = editingItem.roleId
      ? RoleBusiness.update
      : RoleBusiness.insert;
    method(editingItem)
      .then(() => {
        setIsLoading(false);
        saveEvent && saveEvent();
        cancelEvent && cancelEvent();
      })
      .catch((err) => {
        setIsLoading(false);
        ToastService.notify(err.message || err, 'error');
      });
  };

  const onCancel = () => {
    cancelEvent && cancelEvent();
  };

  return (
    <div className="com-role-edit">
      <div className="form-cols-2">
        <span className="form-label">{controlsText.name}：</span>
        <span className="form-value">
          <Input
            onChange={(e) =>
              setEditingItem({ ...editingItem, name: e.target.value })
            }
            value={editingItem.name || ''}
            placeholder={controlsText.name}
            errorMessage={messagesText.required(controlsText.name)}
            showError={submitted && !editingItem.name}
          ></Input>
        </span>
        <span className="form-label">{controlsText.description}：</span>
        <span className="form-value">
          <Input
            onChange={(e) =>
              setEditingItem({ ...editingItem, description: e.target.value })
            }
            value={editingItem.description || ''}
            placeholder={controlsText.description}
            onKeyUp={(e) => e.key === 'Enter' && onSave()}
          ></Input>
        </span>
        <span className="form-label">{controlsText.order}：</span>
        <span className="form-value">
          <Input
            type="number"
            onChange={(e) =>
              setEditingItem({ ...editingItem, order: Number(e.target.value) })
            }
            value={String(editingItem.order || '')}
            placeholder={controlsText.order}
            errorMessage={messagesText.required(controlsText.order)}
            showError={submitted && !editingItem.order}
          ></Input>
        </span>
      </div>
      <div className="button-row">
        <Button state={isLoading ? 3 : 1} onClick={onSave.bind(this)}>
          {controlsText.save}
        </Button>
        <Button role="secondary" onClick={onCancel.bind(this)}>
          {controlsText.cancel}
        </Button>
      </div>
    </div>
  );
};

export default RoleEdit;

// front-end/vue/src/views/roles/role-edit/role-edit.vue
<template>
  <div class="com-role-edit">
    <div class="form-cols-2">
      <span class="form-label">{{controls.name}}：</span>
      <span class="form-value">
        <ctr-input
          v-model="editingItem.name"
          :focus="true"
          :placeholder="controls.name"
          :errorMessage="messages.required(controls.name)"
          :error="submitted && !editingItem.name"></ctr-input>
      </span>
      <span class="form-label">{{controls.description}}：</span>
      <span class="form-value">
        <ctr-input
          v-model="editingItem.description"
          :placeholder="controls.description"
          @enterEvent="onSave"></ctr-input>
      </span>
      <span class="form-label">{{controls.order}}：</span>
      <span class="form-value">
        <ctr-input
          v-model="editingItem.order"
          type="number"
          :placeholder="controls.order"
          :errorMessage="messages.required(controls.order)"
          :error="submitted && !editingItem.order"></ctr-input>
      </span>
    </div>
    <div class="button-row">
      <ctr-button
        :isLoading="loading"
        :text="controls.save"
        @clickEvent="onSave"></ctr-button>
      <ctr-button
        type="secondary"
        :text="controls.cancel"
        @clickEvent="onCancel"></ctr-button>
    </div>
  </div>
</template>

<script lang="ts" src="./role-edit.ts"></script>
<style lang="scss" scoped type="text/css" src="./role-edit.scss"></style>
