// front-end/vue/src/components/user-profile/user-profile.vue
<template>
  <div class="com-user-profile">
    <div class="user-profile" v-if="item">
      <span class="form-label">{{controls.loginName}}：</span>
      <span class="form-value">
        {{item.loginName}}
      </span>

      <span class="form-label">{{controls.fullName}}：</span>
      <span class="form-value">
        {{item.fullName}}
      </span>

      <span class="form-label">{{controls.birthday}}：</span>
      <span class="form-value">
        {{item.birthday}}
      </span>

      <span class="form-label">{{controls.cellphone}}：</span>
      <span class="form-value">
        {{item.cellphone}}
      </span>

      <span class="form-label">{{controls.email}}：</span>
      <span class="form-value">
        {{item.email}}
      </span>

      <span class="form-label">{{controls.roles}}：</span>
      <span class="form-value">
        {{item.roles}}
      </span>

      <span class="form-label">{{controls.remark}}：</span>
      <span class="form-value">
        {{item.remark}}
      </span>
    </div>
  </div>
</template>

<script lang="ts" src="./user-profile.ts"></script>
<style lang="scss" scoped src="./user-profile.scss"></style>

// front-end/react/src/components/user-profile/user-profile.tsx
import React from 'react';
import { User } from '../../models';
import { FormatService, TextService } from '../../utils';
import './user-profile.scss';

export interface ComUserProfileProps {
  item?: User;
}

export const ComUserProfile = ({ item }: ComUserProfileProps) => {
  const controlsText = TextService.controls;

  if (!item) {
    return null;
  }

  return (
    <div className="com-user-profile">
      <div className="user-profile">
        <span className="form-label">{controlsText.loginName}：</span>
        <span className="form-value">{item.loginName}</span>

        <span className="form-label">{controlsText.fullName}：</span>
        <span className="form-value">{item.fullName}</span>

        <span className="form-label">{controlsText.birthday}：</span>
        <span className="form-value">
          {FormatService.formatDate(item.birthday || '', 'yyyy-MM-dd')}
        </span>

        <span className="form-label">{controlsText.cellphone}：</span>
        <span className="form-value">{item.cellphone}</span>

        <span className="form-label">{controlsText.email}：</span>
        <span className="form-value">{item.email}</span>

        <span className="form-label">{controlsText.roles}：</span>
        <span className="form-value">{item.roles}</span>

        <span className="form-label">{controlsText.remark}：</span>
        <span className="form-value">{item.remark}</span>
      </div>
    </div>
  );
};
