// front-end/vue/src/views/user-roles/user-roles.vue
<template>
  <div class="user-roles-view">
    <user-role-list ref="userList" :buttons="tableButtons" :columns="columns"></user-role-list>
    <ctr-dialog :visible="rolesDialogVisible" @closeEvent="rolesDialogVisible = false"
      :title="userRolesText" @cancelEvent="rolesDialogVisible = false">
      <roles-edit @cancelEvent="rolesDialogVisible = false" :item="currentItem" @saveEvent="onSave"></roles-edit>
    </ctr-dialog>
  </div>
</template>

<script lang="ts" src="./user-roles.ts"></script>
<style lang="scss" scoped="" type="text/css" src="./user-roles.scss"></style>

// front-end/react/src/app/userroles/page.tsx
'use client';
import React, { useCallback, useEffect, useState } from 'react';
import { ComUserList } from '../../components';
import { Dialog } from '../../controls';
import { RolesEdit } from './_roles-edit/roles-edit';
import { TextService } from '../../utils';
import { TableButton, TableColumn } from '@/controls/table/table.interface';
import { UserRole } from '../../models';
import './user-roles.scss';

export default function UserRoles() {
  const controlsText = TextService.controls;
  const [tableButtons, setTableButtons] = useState<TableButton[]>([]);
  const [columns, setColumns] = useState<TableColumn[]>([]);
  const [rolesDialogVisible, setRolesDialogVisible] = useState(false);
  const [currentItem, setCurrentItem] = useState<UserRole>();

  const setOptions = useCallback(() => {
    setColumns([
      {
        headerText: controlsText.loginName,
        field: 'loginName',
        click: (item: UserRole) => {
          setCurrentItem(item);
        },
      },
      { headerText: controlsText.fullName, field: 'fullName' },
      { headerText: controlsText.department, field: 'department' },
      { headerText: controlsText.remark, field: 'remark' },
      { headerText: controlsText.roles, field: 'roles' },
    ]);

    setTableButtons([
      {
        buttonText: controlsText.userRoles,
        headerText: controlsText.userRoles,
        click: (item: UserRole) => {
          setRolesDialogVisible(true);
          setCurrentItem(item);
        },
      },
    ]);
  }, [controlsText]);

  useEffect(() => {
    setOptions();
  }, [setOptions]);

  const onSave = () => {
    setRolesDialogVisible(false);
  };

  return (
    <div className="user-roles-view">
      <ComUserList buttons={tableButtons} columns={columns}></ComUserList>
      <Dialog
        visible={rolesDialogVisible}
        onClose={() => setRolesDialogVisible(false)}
        title={controlsText.userRoles}
        onCancel={() => setRolesDialogVisible(false)}
      >
        <RolesEdit
          cancelEvent={() => setRolesDialogVisible(false)}
          item={currentItem}
          saveEvent={onSave}
        ></RolesEdit>
      </Dialog>
    </div>
  );
}
