// front-end/react/src/controls/dialog/dialog.tsx
import { useAppContext } from '@/contexts/app-context';
import { Button } from '..';
import './dialog.scss';
import React from 'react';

export interface DialogProps {
  visible?: boolean;
  title?: string;
  showOkButton?: boolean;
  showCancelButton?: boolean;
  okButtonText?: string;
  cancelButtonText?: string;
  children?: React.ReactNode;
  isLoading?: boolean;
  onClose?: () => void;
  onOk?: () => void;
  onCancel?: () => void;
}

export const Dialog = ({
  visible,
  children,
  title,
  showOkButton = false,
  showCancelButton = false,
  okButtonText,
  cancelButtonText,
  onOk,
  onCancel,
  isLoading,
  onClose,
}: DialogProps) => {
  const { controlsText } = useAppContext();
  const clickBg = (event: React.MouseEvent<HTMLDivElement, MouseEvent>) => {
    onClose && onClose();
    event.stopPropagation();
  };

  return visible ? (
    <div className="ctr-dialog">
      <div onClick={clickBg} className="dialog-bg"></div>
      <div className="dialog-body">
        <span
          onClick={() => onClose && onClose()}
          className="fa fa-close"
        ></span>
        {title && (
          <div className="dialog-title" v-if="title">
            {title}
          </div>
        )}
        <div
          className={['dialog-content', !title ? 'no-title-body' : ''].join(
            ' '
          )}
        >
          {children}
        </div>
        {(showOkButton || showCancelButton) && (
          <div className="dialog-footer">
            <Button onClick={() => onOk && onOk()} state={isLoading ? 3 : 1}>
              {okButtonText || controlsText.ok}
            </Button>
            <Button onClick={() => onCancel && onCancel()} role="secondary">
              {cancelButtonText || controlsText.cancel}
            </Button>
          </div>
        )}
      </div>
    </div>
  ) : null;
};

// front-end/vue/src/controls/dialog/dialog.vue
<template>
  <div class="ctr-dialog" v-show="show" v-if="visible">
    <div class="dialog-bg" @click="modalClickable && onClose()"></div>
    <div class="dialog-body">
      <i @click="onClose" class="fa fa-close"></i>
      <slot name="header"></slot>
      <div class="dialog-title" v-if="title">
        {{ title }}
      </div>
      <div class="dialog-content" :class="!title ? 'no-title-body' : ''">
        <slot></slot>
      </div>
      <div class="dialog-footer" v-if="showOkButton || showCancelButton">
        <ctr-button @clickEvent="onOk" :text="okButtonText" :isLoading="loading"></ctr-button>
        <ctr-button @clickEvent="onCancel" :text="cancelButtonText" type="secondary"></ctr-button>
      </div>
      <slot name="footer"></slot>
    </div>
  </div>
</template>

<script lang="ts" src="./dialog.ts"></script>
<style lang="scss" scoped src="./dialog.scss"></style>
