// front-end/react/src/app/(self)/login/page.tsx
'use client';
import React, { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { Button, Input } from '../../../controls';
import { TextService, ToastService } from '../../../utils';
import { UserBusiness, BaseInfoService } from '../../../business';
import { routeNames } from '../../../router';
import { UserToken } from '../../../models';
import { useAppContext } from '../../../contexts/app-context';
import './login.scss';

export default function Login() {
  const router = useRouter();
  const appContext = useAppContext();
  const [controlsText, setControlsText] = useState(appContext.controlsText);
  const [messagesText, setMessagesText] = useState(appContext.messagesText);
  const [isLoading, setIsLoading] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  const [password, setPassword] = useState('');
  const [userName, setUserName] = useState(
    BaseInfoService.getUser()?.loginName || ''
  );

  useEffect(() => {
    setControlsText(TextService.controls);
    setMessagesText(TextService.messages);
  }, []);

  const login = () => {
    if (isLoading) {
      return;
    }

    setIsLoading(true);
    setSubmitted(true);
    UserBusiness.login(userName, password)
      .then((userToken) => {
        appContext.setUserToken(userToken as UserToken);
        setIsLoading(false);
        router.push(routeNames.home);
      })
      .catch((err) => {
        setIsLoading(false);
        ToastService.notify(err.message || err, 'error');
      });
  };

  const reset = () => {
    setUserName('');
    setPassword('');
    setSubmitted(false);
  };

  return (
    <div className="login-view">
      <div className="form-container">
        <div className="form-container-content">
          <div className="slogan">{messagesText.siteName}</div>
          <div className="form-cols-2 login-form">
            <span className="form-label">{controlsText.userName}：</span>
            <span className="form-value">
              <Input
                value={userName}
                onChange={(e) => setUserName(e.target.value)}
                placeholder={controlsText.userName}
                errorMessage={
                  messagesText.required
                    ? messagesText.required(controlsText.userName)
                    : ''
                }
                showError={submitted && !userName}
              ></Input>
            </span>
            <span className="form-label">{controlsText.password}：</span>
            <span className="form-value">
              <Input
                type="password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                onKeyUp={(e) => e.key === 'Enter' && login()}
                placeholder={controlsText.password}
                errorMessage={
                  messagesText.required
                    ? messagesText.required(controlsText.password)
                    : ''
                }
                showError={submitted && !password}
              ></Input>
            </span>
          </div>
          <div className="button-row">
            <Button state={isLoading ? 3 : 1} onClick={() => login()}>
              {controlsText.login}
            </Button>
            <Button state={isLoading ? 2 : 1} onClick={reset}>
              {controlsText.reset}
            </Button>
          </div>
        </div>
        <div className="form-container-bg"></div>
      </div>
      <div className="copyright">{messagesText.copyright}</div>
    </div>
  );
}

// front-end/vue/src/views/login/login.vue
<template>
  <div class="login-view">
    <div class="form-container">
      <div class="form-container-content">
        <div class="slogan">{{messages.siteName}}</div>
        <div class="form-cols-2 login-form">
          <span class="form-label">{{controls.userName}}：</span>
          <span class="form-value">
            <ctr-input
              v-model="userName"
              :focus="true"
              :placeholder="controls.userName"
              :errorMessage="messages.required(controls.userName)"
              :error="submitted && !userName"></ctr-input>
          </span>
          <span class="form-label">{{controls.password}}：</span>
          <span class="form-value">
            <ctr-input
              type="password"
              v-model="password"
              :placeholder="controls.password"
              :errorMessage="messages.required(controls.password)"
              :error="submitted && !password"
              @enterEvent="login"></ctr-input>
          </span>
        </div>
        <div class="button-row">
          <ctr-button
            :state="loading?3:1"
            :text="controls.login"
            @clickEvent="login"></ctr-button>
          <ctr-button
            :state="loading?2:1"
            :text="controls.reset"
            @clickEvent="reset"></ctr-button>
        </div>
      </div>
      <div class="form-container-bg"></div>
    </div>
    <div class="copyright">{{messages.copyright}}</div>
  </div>
</template>

<script lang="ts" src="./login.ts"></script>
<style lang="scss" scoped="" type="text/css" src="./login.scss"></style>
