// front-end/react/src/controls/tree/tree.tsx
import React, { useEffect, useState } from 'react';
import { deselectItems } from './tree-helper';
import { TreeNodeItem, TreeNode } from './tree-node/tree-node';
import './tree.scss';

export interface TreeProps {
  showCheckbox?: boolean;
  items?: TreeNodeItem[];
  theme?: 'white' | '';
  selectItem?: (item: TreeNodeItem) => void;
}

export const Tree = ({
  items = [],
  showCheckbox,
  theme,
  selectItem,
}: TreeProps) => {
  const [nodes, setNodes] = useState(items);

  useEffect(() => {
    setNodes(items);
  }, [items]);

  const onSelectItem = (menu: TreeNodeItem) => {
    deselectItems(nodes || [], false);
    menu.selected = true;
    selectItem && selectItem(menu);
    setNodes([...nodes]);
  };

  return (
    <div className="ctr-tree">
      <TreeNode
        className="tree-root"
        items={nodes}
        showCheckbox={showCheckbox}
        theme={theme}
        selectItem={(e) => onSelectItem(e)}
      ></TreeNode>
    </div>
  );
};

// front-end/vue/src/controls/tree/tree.vue
<template>
  <div class="ctr-tree">
    <com-tree-node class="tree-root" :items="items" :showCheckbox="showCheckbox" :theme="theme"
      @selectItem="onSelectItem($event)"></com-tree-node>
  </div>
</template>

<script lang="ts" src="./tree.ts"></script>
<style lang="scss" scoped src="./tree.scss"></style>
