// front-end/vue/src/controls/page-bar/page-bar.vue
<template>
  <div class="page-bar">
    <ul class="pagination">
      <li class="xs-hidden page-button" @click="selectPage(1)"><a onclick="this.blur();">&lt;&lt;</a></li><!--
      -->
      <li class="page-button" @click="selectPage(pre)"><a onclick="this.blur();">&lt;</a></li><!--
      -->
      <li class="xs-hidden page-button" v-if="pre2 > 0" @click="selectPage(pre2)"><a onclick="this.blur();">{{ pre2 }}</a>
      </li><!--
      -->
      <li class="page-button" v-if="pre > 0" @click="selectPage(pre)"><a onclick="this.blur();">{{ pre }}</a></li><!--
      -->
      <li class="active page-button"><a @click="selectPage(Number(pageOptions.pageIndex))">{{ pageOptions.pageIndex }}</a>
      </li><!--
      -->
      <li class="page-button" v-if="next <= Number(pageOptions.pageCount)" @click="selectPage(next)"><a
          onclick="this.blur();">{{ next }}</a></li><!--
      -->
      <li class="xs-hidden page-button" v-if="next2 <= Number(pageOptions.pageCount)" @click="selectPage(next2)"><a
          onclick="this.blur();">{{ next2 }}</a></li><!--
      -->
      <li class="page-button" @click="selectPage(next)"><a onclick="this.blur();">&gt;</a></li><!--
      -->
      <li class="xs-hidden page-button" @click="selectPage(Number(pageOptions.pageCount))"><a
          onclick="this.blur();">&gt;&gt;</a>
      </li><!--
      -->
      <li>
        <input v-model="pageNumber" type="number" step="1" class="input-number" @keyup.enter="goPage()" />
        <a class="go-button" @click="goPage()">Go</a>
      </li><!--
      -->
      <li>
        <a>
          <select @change="updatePageSize($event)" v-model="pageOptions.pageSize" class="page-size">
            <option v-for="(pageSize, index) in pageSizes" :key="index" :value='pageSize'>{{ pageSize }}</option>
          </select>
        </a>
      </li><!--
      -->
      <li><span style="padding-left:10px;padding-right:10px;cursor: default;">{{ pageInfo }}</span></li><!--
      -->
      <li class="xs-hidden"><span style="padding-left:10px;padding-right:10px;cursor: default;">{{ itemInfo }}</span></li>
    </ul>
  </div>
</template>

<script lang="ts" src="./page-bar.ts"></script>
<style lang="scss" scoped src="./page-bar.scss"></style>

// front-end/react/src/controls/page-bar/page-bar.tsx
import React, { useCallback, useEffect, useState } from 'react';
import './page-bar.scss';

export interface PageOptions {
  itemCount?: number;
  pageCount?: number;
  pageIndex?: number;
  pageSize?: number;
}

export interface PageBarProps {
  options?: PageOptions;
  changeEvent?: (options: PageOptions) => void;
}

export const PageBar = ({ options, changeEvent }: PageBarProps) => {
  const [pre, setPre] = useState(0);
  const [pre2, setPre2] = useState(0);
  const [next, setNext] = useState(0);
  const [next2, setNext2] = useState(0);
  const [itemInfo, setItemInfo] = useState('');
  const [pageOptions, setPageOptions] = useState<PageOptions>({
    itemCount: 0,
    pageCount: 0,
    pageIndex: 1,
    pageSize: 20,
  });
  const [pageNumber, setPageNumber] = useState<number | string>(0);
  const [pageSizes] = useState([10, 20, 50, 100, 500]);
  const [pageInfo, setPageInfo] = useState('');

  const updatePage = useCallback(
    (currentPage: number, currentPageOptions: PageOptions) => {
      let newPageOptions = currentPageOptions;
      const pageSize = Number(newPageOptions.pageSize) - 0;
      if (pageSize <= 0 || currentPage <= 0) {
        return;
      }

      if (!currentPage) {
        setPageNumber('');
      } else {
        newPageOptions.pageIndex = currentPage;
        setPageOptions(newPageOptions);
      }
      newPageOptions.pageCount = Math.ceil(
        Number(newPageOptions.itemCount) / pageSize
      );
      setPageInfo(
        newPageOptions.itemCount === 0
          ? '0/0'
          : newPageOptions.pageIndex + '/' + newPageOptions.pageCount
      );
      const current = Number(newPageOptions.pageIndex) - 1;
      const to =
        pageSize * (current + 1) > Number(newPageOptions.itemCount)
          ? newPageOptions.itemCount
          : pageSize * (current + 1);
      setPre(Number(newPageOptions.pageIndex) - 1);
      setPre2(Number(newPageOptions.pageIndex) - 2);
      setNext(Number(newPageOptions.pageIndex) + 1);
      setNext2(Number(newPageOptions.pageIndex) + 2);
      setItemInfo(
        newPageOptions.itemCount === 0
          ? '0/0'
          : current * pageSize + 1 + '-' + to + ' / ' + newPageOptions.itemCount
      );
    },
    []
  );

  const initiatize = useCallback(
    (currentPageOptions: PageOptions) => {
      setPageOptions({ ...currentPageOptions, ...options });
      updatePage(Number(currentPageOptions.pageIndex), currentPageOptions);
    },
    [options, updatePage]
  );

  useEffect(() => {
    initiatize(pageOptions);
  }, [initiatize, pageOptions]);

  const goPage = () => {
    if (!isNaN(pageNumber as number)) {
      if (
        Number(pageNumber) - 0 > Number(pageOptions.pageCount) ||
        Number(pageNumber) - 0 < 1 ||
        Number(pageNumber) - 0 === pageOptions.pageIndex
      ) {
        return;
      }
      selectPage(Number(pageNumber) - 0);
    }
  };

  const selectPage = (currentPage: number = 0, forceUpdate = false) => {
    if (
      !forceUpdate &&
      (pageOptions.itemCount === 0 ||
        currentPage === pageOptions.pageIndex ||
        currentPage > Number(pageOptions.pageCount) ||
        currentPage < 1)
    ) {
      return;
    }
    updatePage(currentPage, pageOptions);
    changeEvent && changeEvent({ ...pageOptions });
  };

  const updatePageSize = (event: React.ChangeEvent<HTMLSelectElement>) => {
    if (event.target.value) {
      setPageOptions({ ...pageOptions, pageSize: Number(event.target.value) });
      selectPage(1, true);
    }
  };

  return (
    <div className="page-bar">
      <div className="pagination">
        <span className="xs-hidden page-button" onClick={() => selectPage(1)}>
          <span>&lt;&lt;</span>
        </span>
        <span className="page-button" onClick={() => selectPage(pre)}>
          <span>&lt;</span>
        </span>
        {pre2 <= 0 ? null : (
          <span
            className="xs-hidden page-button"
            onClick={() => selectPage(pre2)}
          >
            <span>{pre2}</span>
          </span>
        )}
        {pre <= 0 ? null : (
          <span className="page-button" onClick={() => selectPage(pre)}>
            <span>{pre}</span>
          </span>
        )}
        <span className="active page-button">
          <span onClick={() => selectPage(pageOptions.pageIndex)}>
            {pageOptions.pageIndex}
          </span>
        </span>
        {next > Number(pageOptions.pageCount) ? null : (
          <span className="page-button" onClick={() => selectPage(next)}>
            <span>{next}</span>
          </span>
        )}
        {next2 > Number(pageOptions.pageCount) ? null : (
          <span
            className="xs-hidden page-button"
            onClick={() => selectPage(next2)}
          >
            <span>{next2}</span>
          </span>
        )}
        <span className="page-button" onClick={() => selectPage(next)}>
          <span>&gt;</span>
        </span>
        <span
          className="xs-hidden page-button"
          onClick={() => selectPage(pageOptions.pageCount)}
        >
          <span>&gt;&gt;</span>
        </span>
        <span>
          <input
            v-model="pageNumber"
            type="number"
            step="1"
            className="input-number"
            onKeyUp={(e) => e.keyCode === 13 && goPage()}
          />
          <span className="go-button" onClick={() => goPage()}>
            Go
          </span>
        </span>
        <span>
          <span>
            <select
              onChange={(e) => updatePageSize(e)}
              defaultValue={pageOptions.pageSize}
              className="page-size"
            >
              {pageSizes.map((pageSize, index) => (
                <option key={index} value={pageSize}>
                  {pageSize}
                </option>
              ))}
            </select>
          </span>
        </span>
        <span>
          <span
            style={{
              paddingLeft: '10px',
              paddingRight: '10px',
              cursor: 'default',
            }}
          >
            {pageInfo}
          </span>
        </span>
        <span className="xs-hidden">
          <span
            style={{
              paddingLeft: '10px',
              paddingRight: '10px',
              cursor: 'default',
            }}
          >
            {itemInfo}
          </span>
        </span>
      </div>
    </div>
  );
};
