// front-end/react/src/app/controls/checkbox/Checkbox.tsx
import React from 'react';
import './checkbox.scss';

export interface CheckboxProps
  extends React.DetailedHTMLProps<
    React.InputHTMLAttributes<HTMLInputElement>,
    HTMLInputElement
  > {}

export const Checkbox = ({
  checked,
  children,
  onClick,
  onChange,
  ...props
}: CheckboxProps) => {
  return (
    <span className="ctr-checkbox">
      <input
        type="checkbox"
        defaultChecked={checked || false}
        onClick={onClick}
        onChange={onChange}
        {...props}
      />
      {children ? <span className="checkbox-text">{children}</span> : null}
    </span>
  );
};

// front-end/vue/src/controls/checkbox/checkbox.vue
<template>
  <span class="ctr-checkbox">
    <input type="checkbox" :checked="Boolean(modelValue)" :class="[customClass]" @click="onClick" />
    <span class="checkbox-text" v-if="text">
      {{ text }}
    </span>
  </span>
</template>

<script lang="ts" src="./checkbox.ts"></script>
<style lang="scss" scoped src="./checkbox.scss"></style>
