// front-end/react/src/app/controls/popup-menu/PopupMenu.tsx
/**
 * position format: vertical-horizontal. e.g. top-left
 */
import React, { ReactNode, useCallback, useEffect, useState } from 'react';
import './popup-menu.scss';
import Link from 'next/link';

export interface PopupMenuItem {
  name: string;
  url?: string;
  click?: Function;
}

export interface PopupMenuProps {
  visible?: boolean;
  position?: string;
  children?: ReactNode;
  items?: PopupMenuItem[];
}

export const PopupMenu = ({
  children,
  visible,
  items,
  position,
}: PopupMenuProps) => {
  const [showPopup, setShowPopup] = useState(visible);
  const [styleObject, setStyleObject] = useState({});
  const [slotWrapperId, setSlotWrapperId] = useState('');

  useEffect(() => {
    setSlotWrapperId('popup-menu-slot-' + new Date().getTime());
  }, []);

  const updatePosition = useCallback(() => {
    setTimeout(() => {
      const slot = document.getElementById(slotWrapperId);
      const popupPosition = (position || getAutoPosition()).split('-');
      setStyleObject({
        [popupPosition[0] || 'top']: (slot ? slot.offsetHeight : 0) + 3 + 'px',
        [popupPosition[1] || 'left']: 0,
      });
    });
  }, [position, slotWrapperId]);

  useEffect(() => {
    updatePosition();
    document.body.addEventListener('click', onClickBody);

    return () => {
      document.body.removeEventListener('click', onClickBody);
    };
  }, [updatePosition]);

  // TODO: calculate the best position
  const getAutoPosition = () => {
    return 'top-left';
  };

  const onClickSlot = () => {
    // execute after body click propagation
    if (!showPopup) {
      setTimeout(() => {
        setShowPopup(true);
      });
    }
  };

  const onClickBody = () => {
    setShowPopup(false);
  };

  const menus = (items || []).map((item, index) => (
    <div
      className="list-item"
      key={index}
      onClick={(e) => item.click && item.click(e)}
    >
      {item.url ? (
        <Link href={item.url} className="list-item-text">
          {item.name}
        </Link>
      ) : (
        <span className="list-item-text">{item.name}</span>
      )}
    </div>
  ));

  return (
    <div className="ctr-popup-menu">
      <div
        id={slotWrapperId}
        className="slot-wrapper"
        onClick={() => onClickSlot()}
      >
        {children}
      </div>
      {showPopup ? (
        <div className="list-wrapper" style={styleObject}>
          {menus}
        </div>
      ) : null}
    </div>
  );
};

// front-end/vue/src/controls/popup-menu/popup-menu.vue
<template>
  <div class="ctr-popup-menu">
    <div :id="slotWrapperId" class="slot-wrapper" @click="onClickSlot">
      <slot></slot>
    </div>
    <div class="list-wrapper" :style="styles" v-if="displayMenu">
      <div class="list-item" v-for="(item, index) in items" :key="index" @click="item.click && item.click($event)">
        <a class="list-item-text" :href="item.url" v-if="item.url">{{ item.name }}</a>
        <span class="list-item-text" v-else>{{ item.name }}</span>
      </div>
    </div>
  </div>
</template>

<script lang="ts" src="./popup-menu.ts"></script>
<style lang="scss" scoped src="./popup-menu.scss"></style>
