// front-end/react/src/app/password/page.tsx
'use client';
import React, { useState } from 'react';
import { Button, Input } from '../../controls';
import { UserBusiness } from '../../business';
import { TextService, ToastService } from '../../utils';
import './password.scss';

export default function Password() {
  const controlsText = TextService.controls;
  const messagesText = TextService.messages;
  const [isLoading, setIsLoading] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  const [originalPassword, setOriginalPassword] = useState('');
  const [newPassword, setNewPassword] = useState('');
  const [passwordConfirm, setPasswordConfirm] = useState('');

  const onSave = () => {
    setIsLoading(true);
    setSubmitted(true);
    UserBusiness.modifyPassword(originalPassword, newPassword, passwordConfirm)
      .then(() => {
        setIsLoading(false);
        setSubmitted(false);
        onReset();
        ToastService.notify(messagesText.succeeded, 'success');
      })
      .catch((err) => {
        setIsLoading(false);
        ToastService.notify(err.message || err, 'error');
      });
  };

  const onReset = () => {
    setOriginalPassword('');
    setNewPassword('');
    setPasswordConfirm('');
    setSubmitted(false);
  };

  return (
    <div className="password-view">
      <div className="form-wrapper">
        <div className="form-password">
          <span className="form-label">{controlsText.originalPassword}：</span>
          <span className="form-value">
            <Input
              type="password"
              onChange={(e) => setOriginalPassword(e.target.value)}
              placeholder={controlsText.originalPassword}
              errorMessage={messagesText.required(
                controlsText.originalPassword
              )}
              showError={submitted && !originalPassword}
            ></Input>
          </span>
          <span className="form-label">{controlsText.newPassword}：</span>
          <span className="form-value">
            <Input
              type="password"
              onChange={(e) => setNewPassword(e.target.value)}
              placeholder={controlsText.newPassword}
              errorMessage={messagesText.required(controlsText.newPassword)}
              showError={submitted && !newPassword}
            ></Input>
          </span>
          <span className="form-label">{controlsText.passwordConfirm}：</span>
          <span className="form-value">
            <Input
              type="password"
              onChange={(e) => setPasswordConfirm(e.target.value)}
              onKeyUp={(e) => e.key === 'Enter' && onSave()}
              placeholder={controlsText.passwordConfirm}
              errorMessage={messagesText.required(controlsText.passwordConfirm)}
              showError={submitted && !passwordConfirm}
            ></Input>
          </span>
        </div>
        <div className="button-row">
          <Button state={isLoading ? 3 : 1} onClick={onSave}>
            {controlsText.save}
          </Button>
          <Button role="secondary" onClick={onReset}>
            {controlsText.reset}
          </Button>
        </div>
      </div>
    </div>
  );
}

// front-end/vue/src/views/password/password.vue
<template>
  <div class="password-view">
    <div class="form-wrapper">
      <div class="form-password">
        <span class="form-label">{{controls.originalPassword}}：</span>
        <span class="form-value">
          <ctr-input
            type="password"
            v-model="originalPassword"
            :focus="true"
            :placeholder="controls.originalPassword"
            :errorMessage="messages.required(controls.originalPassword)"
            :error="submitted && !originalPassword"></ctr-input>
        </span>
        <span class="form-label">{{controls.newPassword}}：</span>
        <span class="form-value">
          <ctr-input
            type="password"
            v-model="newPassword"
            :placeholder="controls.newPassword"
            :errorMessage="messages.required(controls.newPassword)"
            :error="submitted && !newPassword"></ctr-input>
        </span>
        <span class="form-label">{{controls.passwordConfirm}}：</span>
        <span class="form-value">
          <ctr-input
            v-model="passwordConfirm"
            type="password"
            :placeholder="controls.passwordConfirm"
            :errorMessage="messages.required(controls.passwordConfirm)"
            :error="submitted && !passwordConfirm"
            @enterEvent="onSave"></ctr-input>
        </span>
      </div>
      <div class="button-row">
        <ctr-button
          :state="loading?3:1"
          :text="controls.save"
          @clickEvent="onSave"></ctr-button>
        <ctr-button
          type="secondary"
          :text="controls.reset"
          @clickEvent="onReset"></ctr-button>
      </div>
    </div>
  </div>
</template>

<script lang="ts" src="./password.ts"></script>
<style lang="scss" scoped="" type="text/css" src="./password.scss"></style>
