// front-end/vue/src/controls/toolbar/toolbar.vue
<template>
  <div class="ctr-tool-bar">
    <span v-if="buttons.new" class="button-box" @click="onClick('new')">
      <i class="fa fa-plus-square-o"></i>
      <span class="button-text">{{ controls.new }}</span>
    </span>
    <span v-if="buttons.settings" class="button-box" @click="onClick('settings')">
      <i class="fa fa-cog"></i>
      <span class="button-text">{{ controls.settings }}</span>
    </span>
    <span v-if="buttons.chart" class="button-box" @click="onClick('chart')">
      <i class="fa fa-bar-chart"></i>
      <span class="button-text">{{ controls.statistics }}</span>
    </span>
  </div>
</template>

<script lang="ts" src="./toolbar.ts"></script>
<style lang="scss" scoped src="./toolbar.scss"></style>

// front-end/react/src/controls/toolbar/toolbar.tsx
import React from 'react';
import { TextService } from '../../utils';
import './toolbar.scss';

export interface ToolbarProps {
  buttons?: {
    new?: boolean;
    settings?: boolean;
    chart?: boolean;
  };
  clickEvent?: (buttonName: string) => void;
}

export const Toolbar = ({
  buttons = {
    new: true,
  },
  clickEvent,
}: ToolbarProps) => {
  const onClick = (buttonName: string) => {
    clickEvent && clickEvent(buttonName);
  };

  return (
    <div className="ctr-tool-bar">
      {buttons.new === false ? null : (
        <span className="button-box" onClick={() => onClick('new')}>
          <i className="fa fa-plus-square-o"></i>
          <span className="button-text">{TextService.controls.new}</span>
        </span>
      )}
      {!buttons.settings ? null : (
        <span className="button-box" onClick={() => onClick('settings')}>
          <i className="fa fa-cog"></i>
          <span className="button-text">{TextService.controls.settings}</span>
        </span>
      )}
      {!buttons.chart ? null : (
        <span className="button-box" onClick={() => onClick('chart')}>
          <i className="fa fa-bar-chart"></i>
          <span className="button-text">{TextService.controls.statistics}</span>
        </span>
      )}
    </div>
  );
};
